### ISSUE TITLE
Fix broken url on the faq page and state how to cancel subscriptions.

### ISSUE THREAD

**Issue by lGhandley** [thoughtstem/www.learntomod.com#18]
Fix broken terms of use url on the faq www.learntomod.com/faq page and clarify that this a recurring 1 yr subscription and that to opt out of autobilling, they should email us their receipt. (It's not super clear from this faq that this is a recurring 1-yr learntomod subscription.)

Broken Url should be changed to: www.learntomod.com/terms.html

maybe make another bullet point in the faq that specifically addresses how to cancel the subscription?

The parts in the faq that mention refunds are:

What's your refund policy?
Our complete refund policy can be found in our Terms of Use. In short:
Refunds can be made within the first month of the subscription period. However, if you are experiencing technical difficulties, please work with LearnToMod Customer Service before requesting a refund. Customer Service can be contacted at any time at contact@learntomod.com.

What happens when my 1-year subscription expires?
You will be automatically billed for another 1-year subscription. If your payment fails, you may lose access to the software, but we’ll be sure to save all your Minecraft mods & data for you. You can purchase another access key at any time on this site and use it to renew your LearnToMod account. You can cancel your subscription at any time by emailing contact@learntomod.com

**Comment by ldhandley** [comment]
I think I made the fixes you want? Please send more specific language changes if this is still not resolved.
