### ISSUE TITLE
edit emails on Terms of use page and clarify how to cancel subscriptions

### ISSUE THREAD

**Issue by lGhandley** [thoughtstem/www.learntomod.com#19]
update the emails in the terms of use page to contact@learntomod.com. It's not very clear how to cancel subscriptions here or how to opt out autorenewal, just mentions refunds. Maybe say accounts and or subscriptions? 

on point 9.2, put a space between email and contact@learntomod.com

**Comment by ldhandley** [comment]
"It's not very clear how to cancel subscriptions here or how to opt out autorenewal, just mentions refunds." 
If you have language you want me to add, please send language!

"Maybe say accounts and or subscriptions?"
Where?

I went ahead and fixed these two:
1. "update the emails in the terms of use page to contact@learntomod.com."
2. "on point 9.2, put a space between email and contact@learntomod.com"

-
