### ISSUE TITLE
https:// certificate expired on the LearnToMod forum - connection not secure 

### ISSUE THREAD

**Issue by lGhandley** [thoughtstem/www.learntomod.com#20]
The https:// certificate for the learntomod forum has expired or not there.

http://forum.learntomod.com/

In chrome browsers, there's a broken lock next to the url field
![Screenshot (646)](https://user-images.githubusercontent.com/33248445/93291298-473d7d80-f7a8-11ea-8637-4bf055553f86.png)

**Comment by ldhandley** [comment]
Uh oh! Stephen says he can get to this next week.

**Comment by ldhandley** [comment]
We're retiring the forum, so this should get resolved with whatever we move the Forum to.
