### ISSUE TITLE
broken images in learntomod badge index on https://mod.learntomod.com/badge_pointers/9054

### ISSUE THREAD

**Issue by lGhandley** [thoughtstem/www.learntomod.com#21]
Some icon images on forum.learntomod.com broken, but I'm not sure if that's just due to the https:// certificate needing to be renewed.

![Screenshot (648)](https://user-images.githubusercontent.com/33248445/93403857-42330980-f84e-11ea-969b-d6be2819b1cc.png)

**Comment by ldhandley** [comment]
We are planning to retire the Forum, so this should get resolved with whatever we move the Forum to!

**Comment by lGhandley** [comment]
Okay. I'll work on saving the how to section and copying it into a file.
Will we be linking to a freshdesk post to replace the forum? I think that
would be better setting up a facebook group or another offsite group.
