### ISSUE TITLE
Add more detail on www.learntomod.com website about what kind of minecraft is compatible

### ISSUE THREAD

**Issue by lGhandley** [thoughtstem/www.learntomod.com#22]
On the learntomod faq page and the features page, let's add more detail about what kind of minecraft is compatible with learntomod. 

Details to add: Java version only and that it must be downloaded directly from minecraft.net not anywhere else like the microsoft store also our servers currently run on 1.9.2

https://www.learntomod.com/faq/ (what are learntomod's technical requirements?)

maybe change the text to:
* will only work with Mojang's regular Minecraft game (the Java version) downloaded from <a href="https://www.minecraft.net/en-us"minecraft.net<a> for computers / laptops. Versions downloaded from elsewhere will not work with LearnToMod.
* Our servers currently run on 1.9 and 1.9.2. Here's how to make a <a href="https://learntomod.freshdesk.com/en/support/solutions/articles/12000016803-how-to-change-minecraft-versions">1.9 or 1.9.2 profile</a> on your Minecraft launcher.

https://www.learntomod.com/features (at the bottom of the page)

* change the link text font color to white so it's more readable (hex code #ffffff)
change text to:
LearnToMod is compatible with Mojang's paid Java version of Minecraft for computers / laptops. It should be downloaded minecraft.net and not from anywhere else.

**Comment by ldhandley** [comment]
Added these edits!

**Comment by lGhandley** [comment]
Looks good! Don't forget to include on the FAQ section on the
www.learntomod.com website that the paid version of minecraft is necessary,
otherwise people might try getting the free demo version (which won't work)
