### ISSUE TITLE
LearnToMod texture editor not working in Chrome and other browsers

### ISSUE THREAD

**Issue by lGhandley** [thoughtstem/www.learntomod.com#24]
The LearnToMod texture editor is no longer working in Chrome browsers. When I and another teacher open the editor, the popup screen is blank. (I'm using windows 10 with my popup blocker is turned off)

![Screenshot (669)](https://user-images.githubusercontent.com/33248445/95272891-357b5300-0807-11eb-9cf0-392dca9e01e6.png)

**Comment by lGhandley** [comment]
![Screenshot (19)](https://user-images.githubusercontent.com/33248445/96325831-ee544580-0ff0-11eb-8d3d-d0cf62b43d10.png)
![Screenshot (18)](https://user-images.githubusercontent.com/33248445/96325832-eeecdc00-0ff0-11eb-87a5-ecdbaa215f72.png)

**Comment by srfoster** [comment]
Make sure you're on https.

**Comment by srfoster** [comment]
I pushed a fix for this
